### ISSUE TITLE
UltraPIF won't work with libdragons joypad subsystem

### ISSUE THREAD

**Issue by TharathielCB** [jago85/UltraPIF_MCU#1]
Hi @jago85 ,
libdragon implemented a new joypad subsystem. But with that the UltraPIF locks the N64 on a blackscreen. It is working on consoles with stock PIF-IC without any problems.
This means that every new homebrew made on the latest libdragon version will just not work. We did a lot of testing and figured out that commands sent to the PIF from CPU cause either CPU or UltraPIF to lock up. So it seems that the joybus command handling of the UltraPIF won't work.
It happens on this branch, if you want to test it: https://github.com/DragonMinded/libdragon/tree/unstable
Some information about the joypad subsystem: It is fully async, interrupt-driven, and abstracts the differences between N64 and GameCube controllers so that games can transparently support both. It’s sending PIF packets in different ways than LibUltra ever would. It expects an accurate PIF implementation.

Here is a debug log of the Summercart64 which is using the newest libdragon version:
> sc64deployer.exe debug
←[1m[Debug]←[0m: Started
Libdragon IPL3
Total memory:   00800000
stage2  B0001BA0    00000690
Hello from RDRAM    807FF8F8
Segment 00000000    64E36341    00000094    807FF6E0    000001C0    00000005
Segment 00000001    00000001    00000258    800001A0    00000013    00001005
Segment 00000002    00000001    00000270    80031880    0004809D    00001007
Boot flags: 00800000    7D7B7924    00010000    002F0000
At main
Before joypad_init

If we remove the joypad subsystem, the rom loads:
> sc64deployer.exe debug
←[1m[Debug]←[0m: Started
Libdragon IPL3
Total memory:   00800000
stage2  B0001BA0    00000690
Hello from RDRAM    807FF8F8
Segment 00000000    64E36341    00000094    807FF6E0    000001C0    00000005
Segment 00000001    00000001    00000258    800001A0    00000013    00001005
Segment 00000002    00000001    00000270    800304A0    0004577B    00001007
Boot flags: 00800000    41C3CA94    00010000    002F0000
At main
Before timer_init
Before rspq_init
Before rdpq_init
Before dfs_init
Before fonts_init
Loaded atlas 0: 126x63 FMT_I4
Loaded atlas 1: 127x39 FMT_I4
Loaded atlas 2: 11x5 FMT_I4
Before sound_init_default
Before flashcart_init
Before get_tv_type
Before display_init
Before register_VI_handler

I'd like to mention some people as well:
@Meeq, @rasky @Polprzewodnikowy 

PS: @Rasky wants to do some PIF dump traces and add these here, when finished.

**Comment by jago85** [comment]
Apparently, the bug is here:
https://github.com/jago85/UltraPIF_MCU/blob/master/Src%2Fmain.c#L887

It's very specific. The STM32 goes to the HardFault_Handler due to invalid data alignment. 

Since libdragon changed the alignment of the Read Inputs command, the bug is triggered now. The fix is simple, but I'll have to build an updater, which I didn't do for a whole while.

You could insert a 0xFF at index 0 of the command buffer. This should fix the alignment and prevent the crash. It's only necessary for Read Inputs command for the first controller.

**Comment by jago85** [comment]
Stay open until confirmed

**Comment by jago85** [comment]
Looks good. Here is the updater. Also updated the menu to use the IPL2 checksum algo, so it will detect the new IPL3 correctly.

[fw_updater_fpga_0-6-0_mcu_0-11-1_menu_0-10-1_bootfiles.zip](https://github.com/jago85/UltraPIF_MCU/files/14201178/fw_updater_fpga_0-6-0_mcu_0-11-1_menu_0-10-1_bootfiles.zip)

**Comment by TharathielCB** [comment]
Hi, I tested the update yesterday. The Summercart64 works properly with it, except of the reset button. It doesn't matter if it is an in-game reset or the physical button. Do you need further information?

**Comment by AuroraWright** [comment]
> Hi, I tested the update yesterday. The Summercart64 works properly with it, except of the reset button. It doesn't matter if it is an in-game reset or the physical button. Do you need further information?

I have an ultraPIF in my PAL FRA system (with latest fw linked above) and with a SC64 with latest fw the reset button works as you'd expect (I don't have any reset mods, I'm just using the physical button). Not sure if it was fixed on the SC64 side but thought I'd mention it.
